#!/usr/bin/env python3
"""Convert FASTA files with FIM tokens to normal FASTA.

Handles sequences containing <fim_prefix>, <fim_suffix>, <fim_middle> tokens
generated by FIM-trained models. Can either:
1. Reconstruct original sequence order (prefix + middle + suffix)
2. Just strip FIM tokens (keep rearranged order)

Usage:
    # Reconstruct original order (default)
    python script_utils/defim_fasta.py generated.fasta -o clean.fasta

    # Just strip tokens, keep rearranged order
    python script_utils/defim_fasta.py generated.fasta -o clean.fasta --strip_only
"""

from collections import defaultdict
import re

import click

from proxyz.data import dataset


FIM_PATTERN = re.compile("|".join(dataset.FIM_TOKENS))


def parse_fim_sequence(seq: str) -> str:
    """Parse a FIM-formatted sequence into (prefix, middle, suffix).

    Supports both SPM and PSM formats:
    - SPM: <fim_suffix><suffix><fim_prefix><prefix><fim_middle><middle>
    - PSM: <fim_prefix><prefix><fim_suffix><suffix><fim_middle><middle>

    Returns (prefix, middle, suffix) or None if no FIM tokens found.
    """
    segments = defaultdict(str)

    i, state = 0, dataset.FIM_PREFIX
    while True:
        m = FIM_PATTERN.search(seq[i:])
        if m:
            fim_token, k = m.group(0), m.start()
            segments[state] += seq[i: i + k]
            i, state = i + k + len(fim_token), fim_token
        else:
            segments[state] += seq[i:]
            break

    return "".join(
        segments[fim_token] for fim_token in (
            dataset.FIM_PREFIX, dataset.FIM_MIDDLE, dataset.FIM_SUFFIX
        )
    )


def strip_fim_tokens(seq: str) -> str:
    """Remove all FIM tokens from sequence, keeping content in current order."""
    return FIM_PATTERN.sub("", seq)


def process_fasta(input_path: str, output_path: str, strip_only: bool = False):
    """Process FASTA file, converting FIM sequences to normal sequences."""
    with open(output_path, "w") as f:
        for header, seq in dataset.fasta_parse(input_path):
            if strip_only:
                clean_seq = strip_fim_tokens(seq)
            else:
                clean_seq = parse_fim_sequence(seq)
            # Wrap at 60 chars
            f.write(f">{header}\n{dataset.fasta_wrap(clean_seq)}\n")


@click.command(context_settings={'show_default': True})
@click.argument("input_fasta", type=click.Path(exists=True))
@click.option(
    "-o", "--output",
    type=click.Path(),
    default=None,
    help="Output FASTA file. Default: <input>_clean.fasta",
)
@click.option(
    "--strip_only",
    is_flag=True,
    help="Just strip FIM tokens without reconstructing original order.",
)
@click.option("-v", "--verbose", is_flag=True, help="Verbose output.")
def main(input_fasta: str, output: str, strip_only: bool, verbose: bool):
    """Convert FASTA with FIM tokens to normal FASTA.

    By default, reconstructs original sequence order (prefix + middle + suffix).
    Use --strip_only to just remove tokens without reordering.
    """
    if output is None:
        base = input_fasta.rsplit(".", 1)[0]
        output = f"{base}_clean.fasta"

    process_fasta(input_fasta, output, strip_only=strip_only)

    if verbose:
        # Count sequences
        with open(output) as f:
            n_seqs = sum(1 for line in f if line.startswith(">"))
        mode = "strip" if strip_only else "reconstruct"
        print(f"Processed {n_seqs} sequences ({mode} mode)")
        print(f"Output: {output}")
    else:
        print(f"Output: {output}")


if __name__ == "__main__":
    main()
