#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/xyz/modular_xyz.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_xyz.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
import contextlib

from huggingface_hub.dataclasses import strict
from proxyz.utils import attr

from transformers.configuration_utils import PreTrainedConfig
from transformers.modeling_rope_utils import RopeParameters
from transformers.utils import auto_docstring
from transformers.utils.type_validators import interval


@auto_docstring(checkpoint="bigict/ProXYZ")
@strict
class XYZConfig(PreTrainedConfig):
    """
    Configuration for the XYZ U-Net style protein language model.

    A three-stage architecture:

    1. **Char encoder** — transformer at character (residue) granularity
    2. **Token trunk** — transformer at BPE-token granularity
    3. **Char decoder** — transformer at character granularity with U-Net skip
       connections from the encoder

    The char encoder/decoder share the same ``head_dim`` as the trunk so that
    a single ``RotaryEmbedding`` instance can be used across all three stacks.

    This configuration extends [`LlamaConfig`].  All token-level fields
    (``hidden_size``, ``intermediate_size``, ``num_hidden_layers``, etc.) are
    inherited and control the *trunk* transformer.  The char-level fields
    below control the encoder and decoder.

    Constraint: ``char_hidden_size == char_num_attention_heads × head_dim``.

    char_hidden_size (`int`, *optional*, defaults to 2048):
        Hidden size of the char encoder / decoder transformer.
    char_intermediate_size (`int`, *optional*, defaults to 5504):
        FFN intermediate size for char-level layers.
    char_num_hidden_layers (`int`, *optional*, defaults to 4):
        Number of transformer layers in the char encoder and char decoder.
    char_num_attention_heads (`int`, *optional*, defaults to 16):
        Number of attention heads for char-level self-attention.
    char_num_key_value_heads (`int`, *optional*):
        Number of KV heads for GQA at char level.  Defaults to
        ``char_num_attention_heads`` (i.e. multi-head attention) when
        not specified.

    Note:
        ``char_head_dim`` is intentionally omitted — the char stacks reuse the
        token-level ``head_dim`` so that RoPE can be shared.

    Example:
    ```python
    >>> from proxyz.models import XYZConfig, XYZForCausalLM
    >>> config = XYZConfig()
    >>> model = XYZForCausalLM(config)
    ```
    """

    model_type = "xyz"
    keys_to_ignore_at_inference = ["past_key_values", "char_past_key_values"]

    # ---- Tensor-parallel / pipeline-parallel plans (inherited from Llama) ----
    base_model_tp_plan = {
        ".*.layers.*.self_attn.q_proj": "colwise",
        ".*.layers.*.self_attn.k_proj": "colwise",
        ".*.layers.*.self_attn.v_proj": "colwise",
        ".*.layers.*.self_attn.o_proj": "rowwise",
        ".*.layers.*.mlp.gate_proj": "colwise",
        ".*.layers.*.mlp.up_proj": "colwise",
        ".*.layers.*.mlp.down_proj": "rowwise",
    }
    base_model_pp_plan = {
        "embed_tokens": (["input_ids"], ["inputs_embeds"]),
        ".*.layers": (["hidden_states", "attention_mask"], ["hidden_states"]),
        ".*.norm": (["hidden_states"], ["hidden_states"]),
    }

    vocab_size: int = 32000
    hidden_size: int = 4096
    intermediate_size: int = 11008
    num_hidden_layers: int = 32
    num_attention_heads: int = 32
    num_key_value_heads: int | None = None
    hidden_act: str = "silu"
    max_position_embeddings: int = 2048
    initializer_range: float = interval(min=0.0, max=1.0)(default=0.02)
    rms_norm_eps: float = 1e-6
    use_cache: bool = True
    pad_token_id: int | None = None
    bos_token_id: int | None = 1
    eos_token_id: int | list[int] | None = 2
    pretraining_tp: int | None = 1
    tie_word_embeddings: bool = False
    rope_parameters: RopeParameters | dict | None = None
    attention_bias: bool = False
    attention_dropout: int | float | None = 0.0
    mlp_bias: bool = False
    head_dim: int | None = None

    char_hidden_size: int = 2048
    char_intermediate_size: int = 5504
    char_num_hidden_layers: int = 4
    char_num_attention_heads: int = 16
    char_num_key_value_heads: int | None = None

    def __post_init__(self, **kwargs):
        # Default char KV heads to char query heads (MHA) when unspecified.
        if self.char_num_key_value_heads is None:
            self.char_num_key_value_heads = self.char_num_attention_heads
        if self.head_dim is None:
            self.head_dim = self.hidden_size // self.num_attention_heads
        if self.num_key_value_heads is None:
            self.num_key_value_heads = self.num_attention_heads

        super().__post_init__(**kwargs)

    def validate_architecture(self):
        """Part of `@strict`-powered validation. Validates the architecture of the config."""
        # Ensure char_hidden_size is compatible with (char_num_attention_heads, head_dim).
        if self.char_hidden_size != self.char_num_attention_heads * self.head_dim:
            raise ValueError(
                f"The char hidden size ({self.char_hidden_size}) must equal "
                f"char_num_attention_heads ({self.char_num_attention_heads}) × head_dim ({self.head_dim})."
            )
        if self.hidden_size % self.num_attention_heads != 0:
            raise ValueError(
                f"The hidden size ({self.hidden_size}) is not a multiple of the number of attention "
                f"heads ({self.num_attention_heads})."
            )

    @contextlib.contextmanager
    def tokenization(self):
        """Context manager that yields *self* with token-level config active.

        This is a no-op passthrough — the inherited Llama fields already hold
        the token-level values.  Provided for symmetry with ``characterization``.
        """
        yield self

    @contextlib.contextmanager
    def characterization(self):
        """Context manager that temporarily swaps token-level fields with
        char-level equivalents so that ``XYZDecoderLayer`` / ``XYZDecoderLayers``
        can be constructed or invoked with char-granularity dimensions.

        On exit, all fields are restored to their original (token-level) values.
        """
        with attr(
            self,
            hidden_size=self.char_hidden_size,
            intermediate_size=self.char_intermediate_size,
            num_hidden_layers=self.char_num_hidden_layers,
            num_attention_heads=self.char_num_attention_heads,
            num_key_value_heads=self.char_num_key_value_heads,
        ):
            yield self


__all__ = ["XYZConfig"]
