#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/xyz/modular_xyz.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_xyz.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
from collections.abc import Callable
from dataclasses import dataclass
from typing import Optional

import torch
from torch import nn

from transformers.activations import ACT2FN
from transformers.cache_utils import Cache, DynamicCache
from transformers.generation import GenerationMixin
from transformers.integrations import use_kernel_forward_from_hub, use_kernel_func_from_hub, use_kernelized_func
from transformers.masking_utils import create_causal_mask
from transformers.modeling_layers import GenericForSequenceClassification, GradientCheckpointingLayer
from transformers.modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast
from transformers.modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from transformers.modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from transformers.processing_utils import Unpack
from transformers.utils import TransformersKwargs, auto_docstring, can_return_tuple
from transformers.utils.generic import maybe_autocast, merge_with_config_defaults
from transformers.utils.output_capturing import capture_outputs

from .configuration_xyz import XYZConfig


@use_kernel_forward_from_hub("RMSNorm")
class XYZRMSNorm(nn.Module):
    def __init__(self, hidden_size, eps: float = 1e-6) -> None:
        """
        XYZRMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class XYZRotaryEmbedding(nn.Module):
    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    def __init__(self, config: XYZConfig, device=None):
        super().__init__()
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config

        self.rope_type = self.config.rope_parameters["rope_type"]
        rope_init_fn: Callable = self.compute_default_rope_parameters
        if self.rope_type != "default":
            rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]
        inv_freq, self.attention_scaling = rope_init_fn(self.config, device)

        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.register_buffer("original_inv_freq", inv_freq.clone(), persistent=False)

    @staticmethod
    def compute_default_rope_parameters(
        config: XYZConfig | None = None,
        device: Optional["torch.device"] = None,
        seq_len: int | None = None,
    ) -> tuple["torch.Tensor", float]:
        """
        Computes the inverse frequencies according to the original RoPE implementation
        Args:
            config ([`~transformers.PreTrainedConfig`]):
                The model configuration.
            device (`torch.device`):
                The device to use for initialization of the inverse frequencies.
            seq_len (`int`, *optional*):
                The current sequence length. Unused for this type of RoPE.
        Returns:
            Tuple of (`torch.Tensor`, `float`), containing the inverse frequencies for the RoPE embeddings and the
            post-processing scaling factor applied to the computed cos/sin (unused in this type of RoPE).
        """
        base = config.rope_parameters["rope_theta"]
        dim = getattr(config, "head_dim", None) or config.hidden_size // config.num_attention_heads

        attention_factor = 1.0  # Unused in this type of RoPE

        # Compute the inverse frequencies
        inv_freq = 1.0 / (
            base ** (torch.arange(0, dim, 2, dtype=torch.int64).to(device=device, dtype=torch.float) / dim)
        )
        return inv_freq, attention_factor

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with maybe_autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


class XYZMLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=config.mlp_bias)
        self.up_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=config.mlp_bias)
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias=config.mlp_bias)
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
        return down_proj


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


@use_kernel_func_from_hub("rotary_pos_emb")
def apply_rotary_pos_emb(q, k, cos, sin, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = 0.0,
    **kwargs: Unpack[TransformersKwargs],
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        attn_weights = attn_weights + attention_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


@use_kernelized_func(apply_rotary_pos_emb)
class XYZAttention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: XYZConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        self.is_causal = True

        self.q_proj = nn.Linear(
            config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.attention_bias
        )
        self.k_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.v_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.o_proj = nn.Linear(
            config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.attention_bias
        )

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor] | None = None,
        attention_mask: torch.Tensor | None = None,
        past_key_values: Cache | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> tuple[torch.Tensor, torch.Tensor]:
        input_shape = hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)

        query_states = self.q_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        key_states = self.k_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(hidden_shape).transpose(1, 2)

        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

        if past_key_values is not None:
            key_states, value_states = past_key_values.update(key_states, value_states, self.layer_idx)

        attention_interface: Callable = ALL_ATTENTION_FUNCTIONS.get_interface(
            self.config._attn_implementation, eager_attention_forward
        )

        attn_output, attn_weights = attention_interface(
            self,
            query_states,
            key_states,
            value_states,
            attention_mask,
            dropout=0.0 if not self.training else self.attention_dropout,
            scaling=self.scaling,
            **kwargs,
        )

        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        attn_output = self.o_proj(attn_output)
        return attn_output, attn_weights


class XYZDecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: XYZConfig, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size

        self.self_attn = XYZAttention(config=config, layer_idx=layer_idx)

        self.mlp = XYZMLP(config)
        self.input_layernorm = XYZRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = XYZRMSNorm(config.hidden_size, eps=config.rms_norm_eps)

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        use_cache: bool | None = False,
        position_embeddings: tuple[torch.Tensor, torch.Tensor] | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> torch.Tensor:
        residual = hidden_states
        hidden_states = self.input_layernorm(hidden_states)
        # Self Attention
        hidden_states, _ = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            use_cache=use_cache,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        hidden_states = residual + hidden_states

        # Fully Connected
        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)
        hidden_states = self.mlp(hidden_states)
        hidden_states = residual + hidden_states
        return hidden_states


class XYZDecoderLayers(nn.Module):
    def __init__(self, config: XYZConfig):
        super().__init__()
        self.config = config  # FIX: AttributeError: 'XYZDecoderLayers' object has no attribute 'config'

        self.layers = nn.ModuleList(
            [XYZDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = XYZRMSNorm(config.hidden_size, eps=config.rms_norm_eps)

    @merge_with_config_defaults
    @capture_outputs
    @auto_docstring
    def forward(
        self,
        inputs_embeds: torch.FloatTensor,
        causal_mask: torch.Tensor,
        position_embeddings: torch.Tensor,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        use_cache: bool | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPast:
        """
        Runs a stack of [`XYZDecoderLayer`] modules followed by RMS normalization.

        Args:
            inputs_embeds (`torch.FloatTensor` of shape `(batch, seq_len, hidden_size)`):
                Input embeddings (output of a projection or embedding layer).
            causal_mask (`torch.Tensor`):
                Pre-computed causal attention mask.
            position_embeddings (`torch.Tensor`):
                RoPE cos/sin embeddings for the current positions.
            position_ids (`torch.LongTensor`, *optional*):
                Position indices.  Inferred from *past_key_values* when *None*.
            past_key_values (`Cache`, *optional*):
                Key-value cache for incremental decoding.
            use_cache (`bool`, *optional*):
                Whether to populate and return the KV cache.

        Returns:
            [`BaseModelOutputWithPast`] with the normalized hidden states and
            (optionally) the updated KV cache.
        """
        if position_ids is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            position_ids = torch.arange(inputs_embeds.shape[1], device=inputs_embeds.device) + past_seen_tokens
            position_ids = position_ids.unsqueeze(0)

        hidden_states = inputs_embeds
        for decoder_layer in self.layers:
            hidden_states = decoder_layer(
                hidden_states,
                attention_mask=causal_mask,
                position_embeddings=position_embeddings,
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                **kwargs,
            )

        hidden_states = self.norm(hidden_states)
        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values,
        )


@auto_docstring
class XYZPreTrainedModel(PreTrainedModel):
    config: XYZConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["XYZDecoderLayer"]
    _skip_keys_device_placement = ["past_key_values", "char_past_key_values"]
    _supports_flash_attn = True
    _supports_sdpa = True
    _supports_flex_attn = True

    _can_compile_fullgraph = True
    _supports_attention_backend = True
    _can_record_outputs = {
        "hidden_states": XYZDecoderLayer,
        "attentions": XYZAttention,
    }


@auto_docstring
@dataclass
class XYZModelOutputWithPast(BaseModelOutputWithPast):
    """
    Output of [`XYZModel`].

    Extends [`BaseModelOutputWithPast`] with character-granularity outputs from
    the U-Net decoder branch.

    char_last_hidden_state (`torch.Tensor` of shape `(batch, char_seq_len, char_hidden_size)`, *optional*):
        Character-level hidden states from the char decoder.
    char_past_key_values (`Tuple[Cache, Cache]`, *optional*):
        Pair of KV caches — one for the char encoder, one for the char
        decoder — used during incremental generation.
    """

    char_last_hidden_state: torch.FloatTensor | None = None
    char_past_key_values: tuple[Cache, Cache] | None = None
    char_hidden_states: tuple[torch.FloatTensor, ...] | None = None
    char_attentions: tuple[torch.FloatTensor, ...] | None = None


class XYZModel(XYZPreTrainedModel):
    def __init__(self, config: XYZConfig):
        super().__init__(config)

        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.rotary_emb = XYZRotaryEmbedding(config=config)

        # Encoder (character granularity)
        self.to_char_encoder = nn.Sequential(nn.Linear(config.hidden_size, config.char_hidden_size, bias=False))
        with self.config.characterization() as config:
            self.char_encoder = XYZDecoderLayers(config)
        self.from_char_encoder = nn.Sequential(
            nn.Linear(config.char_hidden_size, config.hidden_size, bias=False),
        )

        # Trunk
        with self.config.tokenization() as config:
            self.trunk = XYZDecoderLayers(config)

        # Decoder (character granularity)
        self.to_char_decoder = nn.Sequential(nn.Linear(config.hidden_size, config.char_hidden_size, bias=False))
        with self.config.characterization() as config:
            self.char_decoder = XYZDecoderLayers(config)

        self.gradient_checkpointing = False

    @merge_with_config_defaults
    @capture_outputs
    @auto_docstring
    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        char_input_ids: torch.LongTensor | None = None,
        char_attention_mask: torch.Tensor | None = None,
        char_position_ids: torch.LongTensor | None = None,
        char_past_key_values: tuple[Cache, Cache] | None = None,
        char_inputs_embeds: torch.FloatTensor | None = None,
        repr_char_idx: torch.LongTensor | None = None,
        use_cache: bool | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> XYZModelOutputWithPast:
        """
        U-Net forward pass: char encoder → token trunk → char decoder.

        **Stage 1 — Char encoder.**  Token embeddings are projected to
        *char_hidden_size* and processed by the char encoder stack.

        **Stage 2 — Token trunk.**  Char hidden states are gathered at
        representative positions (``repr_char_idx``), projected back to
        *hidden_size*, and added to the token embeddings.  The result is
        processed by the trunk transformer.

        **Stage 3 — Char decoder.**  Trunk output is projected to
        *char_hidden_size* and scattered back to char positions via
        ``scatter_add`` (skip connection from the trunk).  The char decoder
        stack refines the representation with U-Net skip connections from the
        encoder.

        Args:
            input_ids (`torch.LongTensor` of shape `(batch, token_seq_len)`, *optional*):
                BPE token indices.  Mutually exclusive with *inputs_embeds*.
            attention_mask (`torch.Tensor` of shape `(batch, token_seq_len)`, *optional*):
                Token-level attention mask (1 = attend, 0 = mask).
            position_ids (`torch.LongTensor`, *optional*):
                Token position indices.  Inferred from *past_key_values* when *None*.
            past_key_values (`Cache`, *optional*):
                Trunk KV cache for incremental decoding.
            inputs_embeds (`torch.FloatTensor`, *optional*):
                Pre-computed token embeddings.  Mutually exclusive with *input_ids*.
            char_input_ids (`torch.LongTensor` of shape `(batch, char_seq_len)`, *optional*):
                Character-level token indices.  Mutually exclusive with
                *char_inputs_embeds*.
            char_attention_mask (`torch.Tensor` of shape `(batch, char_seq_len)`, *optional*):
                Character-level attention mask.
            char_position_ids (`torch.LongTensor`, *optional*):
                Character position indices.  Inferred from *char_past_key_values*
                when *None*.
            char_past_key_values (`Tuple[Cache, Cache]`, *optional*):
                Pair of KV caches for the char encoder and char decoder.
            char_inputs_embeds (`torch.FloatTensor`, *optional*):
                Pre-computed char embeddings.  Mutually exclusive with *char_input_ids*.
            repr_char_idx (`torch.LongTensor` of shape `(batch, token_seq_len)`, *optional*):
                Maps each BPE token to its representative character position in
                the char sequence.  Used to gather encoder output into the trunk
                and scatter trunk output back to the decoder.
            use_cache (`bool`, *optional*):
                Whether to populate and return KV caches.

        Returns:
            [`XYZModelOutputWithPast`]:
                - **last_hidden_state** — token-level output from the trunk.
                - **char_last_hidden_state** — char-level output from the char
                  decoder.
                - **past_key_values** / **char_past_key_values** — updated caches.
        """
        # character level.
        if (char_input_ids is None) ^ (char_inputs_embeds is not None):
            raise ValueError("You must specify exactly one of char_input_ids or char_inputs_embeds")

        if char_inputs_embeds is None:
            char_inputs_embeds: torch.Tensor = self.to_char_encoder(self.embed_tokens(char_input_ids))

        if use_cache and char_past_key_values is None:
            with self.config.characterization() as config:
                char_past_key_values = (DynamicCache(config=config), DynamicCache(config=config))

        if char_position_ids is None:
            char_past_seen_tokens = char_past_key_values[0].get_seq_length() if char_past_key_values is not None else 0
            char_position_ids = (
                torch.arange(char_inputs_embeds.shape[1], device=char_inputs_embeds.device) + char_past_seen_tokens
            )
            char_position_ids = char_position_ids.unsqueeze(0)

        char_position_embeddings = self.rotary_emb(char_inputs_embeds, position_ids=char_position_ids)

        # token level
        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if inputs_embeds is None:
            inputs_embeds: torch.Tensor = self.embed_tokens(input_ids)

        if use_cache and past_key_values is None:
            with self.config.tokenization() as config:
                past_key_values = DynamicCache(config=self.config)

        if position_ids is None:
            # position_ids = char_position_ids.expand(
            #     repr_char_idx.shape[0], char_position_ids.shape[1]
            # ).gather(1, repr_char_idx)
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            position_ids = torch.arange(inputs_embeds.shape[1], device=inputs_embeds.device) + past_seen_tokens
            position_ids = position_ids.unsqueeze(0)
        position_embeddings = self.rotary_emb(inputs_embeds, position_ids=position_ids)

        # encode
        with self.config.characterization() as config:
            char_causal_mask = create_causal_mask(
                config=config,
                inputs_embeds=char_inputs_embeds,
                attention_mask=char_attention_mask,
                past_key_values=char_past_key_values[0] if char_past_key_values else None,
                position_ids=char_position_ids,
            )
            encoder_outputs: BaseModelOutputWithPast = self.char_encoder(
                inputs_embeds=char_inputs_embeds,
                causal_mask=char_causal_mask,
                position_embeddings=char_position_embeddings,
                position_ids=char_position_ids,
                past_key_values=char_past_key_values[0] if char_past_key_values else None,
                use_cache=use_cache,
                **kwargs,
            )

        # trunk
        inputs_embeds = inputs_embeds + self.from_char_encoder(
            encoder_outputs.last_hidden_state.gather(
                1, repr_char_idx[..., None].expand(*repr_char_idx.shape, encoder_outputs.last_hidden_state.shape[2])
            )
        )
        with self.config.tokenization() as config:
            causal_mask = create_causal_mask(
                config=config,
                inputs_embeds=inputs_embeds,
                attention_mask=attention_mask,
                past_key_values=past_key_values,
                position_ids=position_ids,
            )

            trunk_outputs: BaseModelOutputWithPast = self.trunk(
                inputs_embeds=inputs_embeds,
                causal_mask=causal_mask,
                position_embeddings=position_embeddings,
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                **kwargs,
            )

        # decode
        trunk_last_hidden_state = self.to_char_decoder(trunk_outputs.last_hidden_state)
        char_inputs_embeds = encoder_outputs.last_hidden_state.scatter_add(  # skip connection
            1, repr_char_idx[..., None].expand_as(trunk_last_hidden_state), trunk_last_hidden_state
        )
        with self.config.characterization() as config:
            decoder_outputs: BaseModelOutputWithPast = self.char_decoder(
                inputs_embeds=char_inputs_embeds,
                causal_mask=char_causal_mask,
                position_embeddings=char_position_embeddings,
                position_ids=char_position_ids,
                past_key_values=char_past_key_values[1] if char_past_key_values else None,
                use_cache=use_cache,
                **kwargs,
            )

        return XYZModelOutputWithPast(
            last_hidden_state=trunk_outputs.last_hidden_state,
            past_key_values=trunk_outputs.past_key_values,
            char_last_hidden_state=decoder_outputs.last_hidden_state,
            char_past_key_values=(encoder_outputs.past_key_values, decoder_outputs.past_key_values),
        )


@auto_docstring
@dataclass
class XYZCausalLMOutputWithPast(CausalLMOutputWithPast):
    """
    Output of [`XYZCausalLMOutputWithPast`].

    Extends [`CausalLMOutputWithPast`] with character-granularity logits and
    hidden states for the auxiliary next-character prediction head.

    char_logits (`torch.FloatTensor` of shape `(batch, char_seq_len, vocab_size)`, *optional*):
        Next-character prediction logits from the char decoder LM head.
    char_last_hidden_state (`torch.Tensor` of shape `(batch, char_seq_len, char_hidden_size)`, *optional*):
        Character-level hidden states from the char decoder.
    char_past_key_values (`Tuple[Cache, Cache]`, *optional*):
        Pair of KV caches — one for the char encoder, one for the char
        decoder — used during incremental generation.
    """

    char_logits: torch.FloatTensor | None = None
    char_past_key_values: tuple[Cache, Cache] | None = None
    char_hidden_states: tuple[torch.FloatTensor, ...] | None = None
    char_attentions: tuple[torch.FloatTensor, ...] | None = None


@auto_docstring
class XYZForCausalLM(XYZPreTrainedModel, GenerationMixin):
    _tied_weights_keys = {"lm_head.weight": "model.embed_tokens.weight"}
    _tp_plan = {"lm_head": "colwise_gather_output"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config: XYZConfig):
        super().__init__(config)
        self.model = XYZModel(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)

        self.char_lm_head = nn.Linear(config.char_hidden_size, config.vocab_size, bias=False)

        # Initialize weights and apply final processing
        self.post_init()

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        labels: torch.LongTensor | None = None,
        logits_to_keep: int | torch.Tensor = 0,
        char_input_ids: torch.LongTensor | None = None,
        char_attention_mask: torch.Tensor | None = None,
        char_position_ids: torch.LongTensor | None = None,
        char_past_key_values: tuple[Cache, Cache] | None = None,
        char_inputs_embeds: torch.FloatTensor | None = None,
        char_labels: torch.LongTensor | None = None,
        char_logits_to_keep: int | torch.Tensor = 0,
        repr_char_idx: torch.LongTensor | None = None,
        use_cache: bool | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> XYZCausalLMOutputWithPast:
        """
        Causal language-modeling forward pass with dual prediction heads.

        Runs the U-Net backbone ([`XYZModel`]) and applies two LM heads:

        - **Next-token** — ``lm_head`` on trunk output → token logits
        - **Next-character** — ``char_lm_head`` on char-decoder output → char logits

        Losses are summed when both *labels* and *char_labels* are provided.

        Args:
            input_ids (`torch.LongTensor` of shape `(batch, token_seq_len)`, *optional*):
                BPE token indices.
            attention_mask (`torch.Tensor`, *optional*):
                Token-level attention mask.
            position_ids (`torch.LongTensor`, *optional*):
                Token position indices.
            past_key_values (`Cache`, *optional*):
                Trunk KV cache.
            inputs_embeds (`torch.FloatTensor`, *optional*):
                Pre-computed token embeddings.
            labels (`torch.LongTensor` of shape `(batch, token_seq_len)`, *optional*):
                Ground-truth token ids for next-token loss.  Shifted internally.
            char_input_ids (`torch.LongTensor` of shape `(batch, char_seq_len)`, *optional*):
                Character-level token indices.
            char_attention_mask (`torch.Tensor`, *optional*):
                Character-level attention mask.
            char_position_ids (`torch.LongTensor`, *optional*):
                Character position indices.
            char_past_key_values (`Tuple[Cache, Cache]`, *optional*):
                Char encoder / decoder KV caches.
            char_inputs_embeds (`torch.FloatTensor`, *optional*):
                Pre-computed char embeddings.
            char_labels (`torch.LongTensor` of shape `(batch, char_seq_len)`, *optional*):
                Ground-truth char ids for next-character loss.  Shifted internally.
            repr_char_idx (`torch.LongTensor`, *optional*):
                Token → representative-char mapping.
            use_cache (`bool`, *optional*):
                Whether to populate and return KV caches.

        Returns:
            [`XYZForCausalLMOutput`]:
                - **loss** — combined next-token + next-character CE loss.
                - **logits** — next-token logits (used by `generate()`).
                - **char_logits** — next-character logits.
        """
        outputs: XYZModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            char_input_ids=char_input_ids,
            char_attention_mask=char_attention_mask,
            char_position_ids=char_position_ids,
            char_past_key_values=char_past_key_values,
            char_inputs_embeds=char_inputs_embeds,
            repr_char_idx=repr_char_idx,
            use_cache=use_cache,
            **kwargs,
        )

        # trunk
        hidden_states = outputs.last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **kwargs)

        # decoder
        char_hidden_states = outputs.char_last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = (
            slice(-char_logits_to_keep, None) if isinstance(char_logits_to_keep, int) else char_logits_to_keep
        )
        char_logits = self.char_lm_head(char_hidden_states[:, slice_indices, :])

        char_loss = None
        if char_labels is not None:
            char_loss = self.loss_function(
                logits=char_logits, labels=char_labels, vocab_size=self.config.vocab_size, **kwargs
            )

        # TODO: weighted sum
        if loss is not None and char_loss is not None:
            loss = loss + char_loss
        elif char_loss is not None:
            loss = char_loss

        return XYZCausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
            char_logits=char_logits,
            char_past_key_values=outputs.char_past_key_values,
            char_hidden_states=outputs.char_hidden_states,
            char_attentions=outputs.char_attentions,
        )

    def prepare_inputs_for_generation(
        self,
        input_ids,
        past_key_values=None,
        attention_mask=None,
        inputs_embeds=None,
        **kwargs,
    ):
        return None


class XYZForSequenceClassification(GenericForSequenceClassification, XYZPreTrainedModel):
    pass


__all__ = [
    "XYZPreTrainedModel",
    "XYZModelOutputWithPast",
    "XYZModel",
    "XYZCausalLMOutputWithPast",
    "XYZForCausalLM",
    "XYZForSequenceClassification",
]
