#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/xyz/modular_xyz.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_xyz.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
import contextlib
from collections.abc import Callable
from dataclasses import dataclass
from typing import Optional

import torch
from torch import nn

from transformers.activations import ACT2FN
from transformers.cache_utils import Cache, DynamicCache
from transformers.generation import GenerationMixin
from transformers.integrations import use_kernel_forward_from_hub, use_kernel_func_from_hub, use_kernelized_func
from transformers.masking_utils import create_causal_mask
from transformers.modeling_layers import (
    GenericForSequenceClassification,
    GenericForTokenClassification,
    GradientCheckpointingLayer,
)
from transformers.modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast, TokenClassifierOutput
from transformers.modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from transformers.modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from transformers.processing_utils import Unpack
from transformers.utils import TransformersKwargs, auto_docstring, can_return_tuple
from transformers.utils.generic import maybe_autocast, merge_with_config_defaults
from transformers.utils.output_capturing import capture_outputs

from .configuration_xyz import XYZConfig
from .processing_xyz import XYZProcessor


@use_kernel_forward_from_hub("RMSNorm")
class XYZRMSNorm(nn.Module):
    def __init__(self, hidden_size, eps: float = 1e-6) -> None:
        """
        XYZRMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class XYZRotaryEmbedding(nn.Module):
    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    def __init__(self, config: XYZConfig, device=None):
        super().__init__()
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config

        self.rope_type = self.config.rope_parameters["rope_type"]
        rope_init_fn: Callable = self.compute_default_rope_parameters
        if self.rope_type != "default":
            rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]
        inv_freq, self.attention_scaling = rope_init_fn(self.config, device)

        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.register_buffer("original_inv_freq", inv_freq.clone(), persistent=False)

    @staticmethod
    def compute_default_rope_parameters(
        config: XYZConfig | None = None,
        device: Optional["torch.device"] = None,
        seq_len: int | None = None,
    ) -> tuple["torch.Tensor", float]:
        """
        Computes the inverse frequencies according to the original RoPE implementation
        Args:
            config ([`~transformers.PreTrainedConfig`]):
                The model configuration.
            device (`torch.device`):
                The device to use for initialization of the inverse frequencies.
            seq_len (`int`, *optional*):
                The current sequence length. Unused for this type of RoPE.
        Returns:
            Tuple of (`torch.Tensor`, `float`), containing the inverse frequencies for the RoPE embeddings and the
            post-processing scaling factor applied to the computed cos/sin (unused in this type of RoPE).
        """
        base = config.rope_parameters["rope_theta"]
        dim = getattr(config, "head_dim", None) or config.hidden_size // config.num_attention_heads

        attention_factor = 1.0  # Unused in this type of RoPE

        # Compute the inverse frequencies
        inv_freq = 1.0 / (
            base ** (torch.arange(0, dim, 2, dtype=torch.int64).to(device=device, dtype=torch.float) / dim)
        )
        return inv_freq, attention_factor

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with maybe_autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


class XYZMLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=config.mlp_bias)
        self.up_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=config.mlp_bias)
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias=config.mlp_bias)
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
        return down_proj


class XYZDistogram(nn.Module):
    def __init__(self, config: XYZConfig):
        super().__init__()
        self.config = config

        self.left_proj = nn.Linear(config.char_hidden_size, config.distogram_intermediate_size)
        self.right_proj = nn.Linear(config.char_hidden_size, config.distogram_intermediate_size)
        self.out_proj = nn.Linear(config.distogram_intermediate_size**2, config.distogram_bins_num)
        self.act_fn = ACT2FN[config.hidden_act]
        self.eps = 1e-8

    def forward(self, x: torch.FloatTensor, labels: torch.LongTensor | None = None, **kwargs) -> torch.FloatTensor:
        # x = torch.einsum(
        #     "... i c, ... j d -> ... i j c d", self.left_proj(x), self.right_proj(x)
        # )
        # x = x.view(*x.shape[:-2], -1)
        # return self.out_proj(self.act_fn((x + x.transpose(-2, -3)) / 2))  # symmetrize

        # Decompose the bilinear form to avoid materializing (B, L, L, D²).
        # Reshape out_proj weight: (bins, D²) -> (bins, D, D)
        d = self.config.distogram_intermediate_size
        x = torch.einsum(
            "k c d, ... i c, ... j d -> ... i j k",
            self.out_proj.weight.view(self.config.distogram_bins_num, d, d),
            self.act_fn(self.left_proj(x)),
            self.act_fn(self.right_proj(x)),
        )
        # Symmetrize on (B, L, L, bins) and add bias
        x = (x + x.transpose(-2, -3)) / 2
        if self.out_proj.bias is not None:
            x = x + self.out_proj.bias
        return x.contiguous()  # FIX: self.loss_function


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


@use_kernel_func_from_hub("rotary_pos_emb")
def apply_rotary_pos_emb(q, k, cos, sin, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = 0.0,
    **kwargs: Unpack[TransformersKwargs],
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        attn_weights = attn_weights + attention_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


@use_kernelized_func(apply_rotary_pos_emb)
class XYZAttention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: XYZConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        self.is_causal = True

        self.q_proj = nn.Linear(
            config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.attention_bias
        )
        self.k_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.v_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.o_proj = nn.Linear(
            config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.attention_bias
        )

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor] | None = None,
        attention_mask: torch.Tensor | None = None,
        past_key_values: Cache | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> tuple[torch.Tensor, torch.Tensor]:
        input_shape = hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)

        query_states = self.q_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        key_states = self.k_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(hidden_shape).transpose(1, 2)

        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

        if past_key_values is not None:
            key_states, value_states = past_key_values.update(key_states, value_states, self.layer_idx)

        attention_interface: Callable = ALL_ATTENTION_FUNCTIONS.get_interface(
            self.config._attn_implementation, eager_attention_forward
        )

        attn_output, attn_weights = attention_interface(
            self,
            query_states,
            key_states,
            value_states,
            attention_mask,
            dropout=0.0 if not self.training else self.attention_dropout,
            scaling=self.scaling,
            **kwargs,
        )

        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        attn_output = self.o_proj(attn_output)
        return attn_output, attn_weights


class XYZDecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: XYZConfig, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size

        self.self_attn = XYZAttention(config=config, layer_idx=layer_idx)

        self.mlp = XYZMLP(config)
        self.input_layernorm = XYZRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = XYZRMSNorm(config.hidden_size, eps=config.rms_norm_eps)

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        use_cache: bool | None = False,
        position_embeddings: tuple[torch.Tensor, torch.Tensor] | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> torch.Tensor:
        residual = hidden_states
        hidden_states = self.input_layernorm(hidden_states)
        # Self Attention
        hidden_states, _ = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            use_cache=use_cache,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        hidden_states = residual + hidden_states

        # Fully Connected
        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)
        hidden_states = self.mlp(hidden_states)
        hidden_states = residual + hidden_states
        return hidden_states


class XYZDecoderLayers(nn.Module):
    def __init__(self, config: XYZConfig):
        super().__init__()
        self.config = config  # FIX: AttributeError: 'XYZDecoderLayers' object has no attribute 'config'

        self.layers = nn.ModuleList(
            [XYZDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = XYZRMSNorm(config.hidden_size, eps=config.rms_norm_eps)

    @merge_with_config_defaults
    @capture_outputs
    @auto_docstring
    def forward(
        self,
        inputs_embeds: torch.FloatTensor,
        causal_mask: torch.Tensor,
        position_embeddings: torch.Tensor,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        use_cache: bool | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPast:
        """
        Runs a stack of [`XYZDecoderLayer`] modules followed by RMS normalization.

        Args:
            inputs_embeds (`torch.FloatTensor` of shape `(batch, seq_len, hidden_size)`):
                Input embeddings (output of a projection or embedding layer).
            causal_mask (`torch.Tensor`):
                Pre-computed causal attention mask.
            position_embeddings (`torch.Tensor`):
                RoPE cos/sin embeddings for the current positions.
            position_ids (`torch.LongTensor`, *optional*):
                Position indices.  Inferred from *past_key_values* when *None*.
            past_key_values (`Cache`, *optional*):
                Key-value cache for incremental decoding.
            use_cache (`bool`, *optional*):
                Whether to populate and return the KV cache.

        Returns:
            [`BaseModelOutputWithPast`] with the normalized hidden states and
            (optionally) the updated KV cache.
        """
        if position_ids is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            position_ids = torch.arange(inputs_embeds.shape[1], device=inputs_embeds.device) + past_seen_tokens
            position_ids = position_ids.unsqueeze(0)

        hidden_states = inputs_embeds
        for decoder_layer in self.layers:
            hidden_states = decoder_layer(
                hidden_states,
                attention_mask=causal_mask,
                position_embeddings=position_embeddings,
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                **kwargs,
            )

        hidden_states = self.norm(hidden_states)
        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values,
        )


@auto_docstring
class XYZPreTrainedModel(PreTrainedModel):
    config: XYZConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["XYZDecoderLayer"]
    _skip_keys_device_placement = ["past_key_values", "char_past_key_values"]
    _supports_flash_attn = True
    _supports_sdpa = True
    _supports_flex_attn = True

    _can_compile_fullgraph = True
    _supports_attention_backend = True
    _can_record_outputs = {
        "hidden_states": XYZDecoderLayer,
        "attentions": XYZAttention,
    }


@auto_docstring
@dataclass
class XYZModelOutputWithPast(BaseModelOutputWithPast):
    """
    Output of [`XYZModel`].

    Extends [`BaseModelOutputWithPast`] with character-granularity outputs from
    the U-Net decoder branch.

    char_last_hidden_state (`torch.Tensor` of shape `(batch, char_seq_len, char_hidden_size)`, *optional*):
        Character-level hidden states from the char decoder.
    char_past_key_values (`tuple[Cache, Cache]`, *optional*):
        Pair of KV caches — one for the char encoder, one for the char
        decoder — used during incremental generation.
    char_hidden_states (`tuple[torch.FloatTensor]`, *optional*):
        Char-decoder hidden states at every layer (returned when
        ``output_hidden_states=True``).  Each element has shape
        `(batch, char_seq_len, char_hidden_size)`.
    char_attentions (`tuple[torch.FloatTensor]`, *optional*):
        Char-decoder self-attention weights at every layer (returned when
        ``output_attentions=True``).  Each element has shape
        `(batch, num_heads, char_seq_len, char_seq_len)`.
    """

    char_last_hidden_state: torch.FloatTensor | None = None
    char_past_key_values: tuple[Cache, Cache] | None = None
    char_hidden_states: tuple[torch.FloatTensor, ...] | None = None
    char_attentions: tuple[torch.FloatTensor, ...] | None = None


class XYZModel(XYZPreTrainedModel):
    def __init__(self, config: XYZConfig):
        super().__init__(config)

        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.rotary_emb = XYZRotaryEmbedding(config=config)

        # Encoder (character granularity)
        if config.has_characterization:
            self.to_char_encoder = nn.Sequential(nn.Linear(config.hidden_size, config.char_hidden_size, bias=False))
            with self.config.characterization() as config:
                self.char_encoder = XYZDecoderLayers(config)
            self.from_char_encoder = nn.Sequential(
                nn.Linear(config.char_hidden_size, config.hidden_size, bias=False),
            )

        # Trunk
        with self.config.tokenization() as config:
            self.trunk = XYZDecoderLayers(config)

        # Decoder (character granularity)
        if config.has_characterization:
            self.to_char_decoder = nn.Sequential(nn.Linear(config.hidden_size, config.char_hidden_size, bias=False))
            with self.config.characterization() as config:
                self.char_decoder = XYZDecoderLayers(config)

        self.gradient_checkpointing = False

    @merge_with_config_defaults
    @capture_outputs
    @auto_docstring
    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        char_input_ids: torch.LongTensor | None = None,
        char_attention_mask: torch.Tensor | None = None,
        char_position_ids: torch.LongTensor | None = None,
        char_past_key_values: tuple[Cache, Cache] | None = None,
        char_inputs_embeds: torch.FloatTensor | None = None,
        repr_char_idx: torch.LongTensor | None = None,
        use_cache: bool | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> XYZModelOutputWithPast:
        """
        U-Net forward pass: char encoder → token trunk → char decoder.

        **Stage 1 — Char encoder.**  Token embeddings are projected to
        *char_hidden_size* and processed by the char encoder stack.

        **Stage 2 — Token trunk.**  Char hidden states are gathered at
        representative positions (``repr_char_idx``), projected back to
        *hidden_size*, and added to the token embeddings.  The result is
        processed by the trunk transformer.

        **Stage 3 — Char decoder.**  Trunk output is projected to
        *char_hidden_size* and scattered back to char positions via
        ``scatter_add`` (skip connection from the trunk).  The char decoder
        stack refines the representation with U-Net skip connections from the
        encoder.

        Args:
            input_ids (`torch.LongTensor` of shape `(batch, token_seq_len)`, *optional*):
                BPE token indices.  Mutually exclusive with *inputs_embeds*.
            attention_mask (`torch.Tensor` of shape `(batch, token_seq_len)`, *optional*):
                Token-level attention mask (1 = attend, 0 = mask).
            position_ids (`torch.LongTensor`, *optional*):
                Token position indices.  Inferred from *past_key_values* when *None*.
            past_key_values (`Cache`, *optional*):
                Trunk KV cache for incremental decoding.
            inputs_embeds (`torch.FloatTensor`, *optional*):
                Pre-computed token embeddings.  Mutually exclusive with *input_ids*.
            char_input_ids (`torch.LongTensor` of shape `(batch, char_seq_len)`, *optional*):
                Character-level token indices.  Mutually exclusive with
                *char_inputs_embeds*.
            char_attention_mask (`torch.Tensor` of shape `(batch, char_seq_len)`, *optional*):
                Character-level attention mask.
            char_position_ids (`torch.LongTensor`, *optional*):
                Character position indices.  Inferred from *char_past_key_values*
                when *None*.
            char_past_key_values (`tuple[Cache, Cache]`, *optional*):
                Pair of KV caches for the char encoder and char decoder.
            char_inputs_embeds (`torch.FloatTensor`, *optional*):
                Pre-computed char embeddings.  Mutually exclusive with *char_input_ids*.
            repr_char_idx (`torch.LongTensor` of shape `(batch, token_seq_len)`, *optional*):
                Maps each BPE token to its representative character position in
                the char sequence.  Used to gather encoder output into the trunk
                and scatter trunk output back to the decoder.
            use_cache (`bool`, *optional*):
                Whether to populate and return KV caches.

        Returns:
            [`XYZModelOutputWithPast`]:
                - **last_hidden_state** — token-level output from the trunk.
                - **char_last_hidden_state** — char-level output from the char
                  decoder.
                - **past_key_values** / **char_past_key_values** — updated caches.
        """
        # character level.
        if self.config.has_characterization:
            if (char_input_ids is None) ^ (char_inputs_embeds is not None):
                raise ValueError("You must specify exactly one of char_input_ids or char_inputs_embeds")

            if char_inputs_embeds is None:
                char_inputs_embeds: torch.Tensor = self.to_char_encoder(self.embed_tokens(char_input_ids))

            # if use_cache and char_past_key_values is None:
            #     with self.config.characterization() as config:
            #         char_past_key_values = (
            #             DynamicCache(config=config), DynamicCache(config=config)
            #         )

            if char_position_ids is None:
                char_past_seen_tokens = (
                    char_past_key_values[0].get_seq_length() if char_past_key_values is not None else 0
                )
                char_position_ids = (
                    torch.arange(char_inputs_embeds.shape[1], device=char_inputs_embeds.device) + char_past_seen_tokens
                )
                char_position_ids = char_position_ids.unsqueeze(0)

            char_position_embeddings = self.rotary_emb(char_inputs_embeds, position_ids=char_position_ids)

        # token level
        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if inputs_embeds is None:
            inputs_embeds: torch.Tensor = self.embed_tokens(input_ids)

        if use_cache and past_key_values is None:
            with self.config.tokenization() as config:
                past_key_values = DynamicCache(config=self.config)

        if self.config.has_characterization and self.config.use_char_position_ids:  # gather from `char_position_ids`
            position_ids = char_position_ids
            if char_position_ids.shape[0] != repr_char_idx.shape[0]:
                assert char_position_ids.shape[0] == 1
                position_ids = position_ids.expand(repr_char_idx.shape[0], char_position_ids.shape[1])
            position_ids = position_ids.gather(1, repr_char_idx)
        elif position_ids is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            position_ids = torch.arange(inputs_embeds.shape[1], device=inputs_embeds.device) + past_seen_tokens
            position_ids = position_ids.unsqueeze(0)
        position_embeddings = self.rotary_emb(inputs_embeds, position_ids=position_ids)

        # encode
        if self.config.has_characterization:
            with self.config.characterization() as config:
                char_causal_mask = create_causal_mask(
                    config=config,
                    inputs_embeds=char_inputs_embeds,
                    attention_mask=char_attention_mask,
                    past_key_values=char_past_key_values[0] if char_past_key_values else None,
                    position_ids=char_position_ids,
                )
                encoder_outputs: BaseModelOutputWithPast = self.char_encoder(
                    inputs_embeds=char_inputs_embeds,
                    causal_mask=char_causal_mask,
                    position_embeddings=char_position_embeddings,
                    position_ids=char_position_ids,
                    past_key_values=char_past_key_values[0] if char_past_key_values else None,
                    use_cache=use_cache,
                    **kwargs,
                )
            inputs_embeds = inputs_embeds + self.from_char_encoder(
                encoder_outputs.last_hidden_state.gather(
                    1,
                    repr_char_idx[..., None].expand(*repr_char_idx.shape, encoder_outputs.last_hidden_state.shape[2]),
                )
            )

        # trunk
        with self.config.tokenization() as config:
            causal_mask = create_causal_mask(
                config=config,
                inputs_embeds=inputs_embeds,
                attention_mask=attention_mask,
                past_key_values=past_key_values,
                position_ids=position_ids,
            )

            trunk_outputs: BaseModelOutputWithPast = self.trunk(
                inputs_embeds=inputs_embeds,
                causal_mask=causal_mask,
                position_embeddings=position_embeddings,
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                **kwargs,
            )

        # decode
        if self.config.has_characterization:
            trunk_last_hidden_state = self.to_char_decoder(trunk_outputs.last_hidden_state)
            char_inputs_embeds = encoder_outputs.last_hidden_state.scatter_add(  # skip connection
                1, repr_char_idx[..., None].expand_as(trunk_last_hidden_state), trunk_last_hidden_state
            )
            with self.config.characterization() as config:
                decoder_outputs: BaseModelOutputWithPast = self.char_decoder(
                    inputs_embeds=char_inputs_embeds,
                    causal_mask=char_causal_mask,
                    position_embeddings=char_position_embeddings,
                    position_ids=char_position_ids,
                    past_key_values=char_past_key_values[1] if char_past_key_values else None,
                    use_cache=use_cache,
                    **kwargs,
                )

            return XYZModelOutputWithPast(
                last_hidden_state=trunk_outputs.last_hidden_state,
                past_key_values=trunk_outputs.past_key_values,
                char_last_hidden_state=decoder_outputs.last_hidden_state,
                char_past_key_values=(encoder_outputs.past_key_values, decoder_outputs.past_key_values),
            )

        return XYZModelOutputWithPast(
            last_hidden_state=trunk_outputs.last_hidden_state,
            past_key_values=trunk_outputs.past_key_values,
        )


@auto_docstring
@dataclass
class XYZCausalLMOutputWithPast(CausalLMOutputWithPast):
    """
    Output of [`XYZCausalLMOutputWithPast`].

    Extends [`CausalLMOutputWithPast`] with character-granularity logits and
    hidden states for the auxiliary next-character prediction head.

    offset_mapping (`torch.LongTensor` of shape `(batch, token_seq_len, 2)`, *optional*):
        A list of (start_char, end_char) tuples for each token, mapping tokens back to
        the original text characters.
    char_logits (`torch.FloatTensor` of shape `(batch, char_seq_len, vocab_size)`, *optional*):
        Next-character prediction logits from the char decoder LM head.
    char_loss (`torch.FloatTensor` of shape `(1,)`, *optional*, returned when
        `char_labels` is provided): Language modeling loss (for next-character prediction)
    char_past_key_values (`tuple[Cache, Cache]`, *optional*):
        Pair of KV caches — one for the char encoder, one for the char
        decoder — used during incremental generation.
    char_hidden_states (`tuple[torch.FloatTensor]`, *optional*):
        Char-decoder hidden states at every layer (returned when
        ``output_hidden_states=True``).
    char_attentions (`tuple[torch.FloatTensor]`, *optional*):
        Char-decoder self-attention weights at every layer (returned when
        ``output_attentions=True``).
    cle_logits (`torch.FloatTensor` of shape `(batch, char_seq_len, cle_vocab_size)`, *optional*):
        CLE (Cα–Local–Environment) classification logits from the
        auxiliary CLE head.
    cle_loss (`torch.FloatTensor` of shape `(1,)`, *optional*, returned when
        `cle_labels` is provided): Language token-classification style loss (for
        character-classification prediction)
    distogram_logits (`torch.FloatTensor` of shape `(batch, char_seq_len, char_seq_len, distogram_bins_num)`, *optional*):
        Pairwise residue–residue distance-bin logits from the distogram
        head.
    distogram_loss (`torch.FloatTensor` of shape `(1,)`, *optional*, returned when
        `distogram_labels` is provided): Language token-classification style loss (for
        character pairwise distogram prediction)
    """

    offset_mapping: torch.LongTensor | None = None
    char_logits: torch.FloatTensor | None = None
    char_loss: torch.FloatTensor | None = None
    char_past_key_values: tuple[Cache, Cache] | None = None
    char_hidden_states: tuple[torch.FloatTensor, ...] | None = None
    char_attentions: tuple[torch.FloatTensor, ...] | None = None
    cle_logits: torch.FloatTensor | None = None
    cle_loss: torch.FloatTensor | None = None
    distogram_logits: torch.FloatTensor | None = None
    distogram_loss: torch.FloatTensor | None = None


@auto_docstring
class XYZForCausalLM(XYZPreTrainedModel, GenerationMixin):
    _tied_weights_keys = {"lm_head.weight": "model.embed_tokens.weight"}
    _tp_plan = {"lm_head": "colwise_gather_output"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config: XYZConfig):
        super().__init__(config)
        self.model = XYZModel(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)

        if config.has_char_lm_head:
            self.char_lm_head = nn.Linear(config.char_hidden_size, config.vocab_size, bias=False)
        if config.has_cle_lm_head:
            self.cle_lm_head = nn.Linear(config.char_hidden_size, config.cle_vocab_size, bias=False)
        if config.has_distogram_lm_head:
            # self.distogram_head = nn.Sequential(
            #     nn.Linear(config.char_hidden_size, config.char_hidden_size, bias=False),
            #     nn.GELU(),
            #     nn.Linear(config.char_hidden_size, config.distogram_bins_num, bias=False),
            # )
            self.distogram_head = XYZDistogram(config)

        # Initialize weights and apply final processing
        self.post_init()

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        labels: torch.LongTensor | None = None,
        logits_to_keep: int | torch.Tensor = 0,
        char_input_ids: torch.LongTensor | None = None,
        char_attention_mask: torch.Tensor | None = None,
        char_position_ids: torch.LongTensor | None = None,
        char_past_key_values: tuple[Cache, Cache] | None = None,
        char_inputs_embeds: torch.FloatTensor | None = None,
        char_labels: torch.LongTensor | None = None,
        char_logits_to_keep: int | torch.Tensor = 0,
        cle_labels: torch.LongTensor | None = None,
        distogram_labels: torch.LongTensor | None = None,
        repr_char_idx: torch.LongTensor | None = None,
        use_cache: bool | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> XYZCausalLMOutputWithPast:
        """
        Causal language-modeling forward pass with dual prediction heads.

        Runs the U-Net backbone ([`XYZModel`]) and applies two LM heads:

        - **Next-token** — ``lm_head`` on trunk output → token logits
        - **Next-character** — ``char_lm_head`` on char-decoder output → char logits

        Losses are summed when both *labels* and *char_labels* are provided.

        Args:
            input_ids (`torch.LongTensor` of shape `(batch, token_seq_len)`, *optional*):
                BPE token indices.
            attention_mask (`torch.Tensor`, *optional*):
                Token-level attention mask.
            position_ids (`torch.LongTensor`, *optional*):
                Token position indices.
            past_key_values (`Cache`, *optional*):
                Trunk KV cache.
            inputs_embeds (`torch.FloatTensor`, *optional*):
                Pre-computed token embeddings.
            labels (`torch.LongTensor` of shape `(batch, token_seq_len)`, *optional*):
                Ground-truth token ids for next-token loss.  Shifted internally.
            logits_to_keep (`int` or `torch.Tensor`, *optional*, defaults to 0):
                If an int, only compute logits for the last ``logits_to_keep``
                token positions (saves memory during training).  If a tensor,
                used as an explicit slice / boolean mask.
            char_input_ids (`torch.LongTensor` of shape `(batch, char_seq_len)`, *optional*):
                Character-level token indices.
            char_attention_mask (`torch.Tensor`, *optional*):
                Character-level attention mask.
            char_position_ids (`torch.LongTensor`, *optional*):
                Character position indices.
            char_past_key_values (`tuple[Cache, Cache]`, *optional*):
                Char encoder / decoder KV caches.
            char_inputs_embeds (`torch.FloatTensor`, *optional*):
                Pre-computed char embeddings.
            char_labels (`torch.LongTensor` of shape `(batch, char_seq_len)`, *optional*):
                Ground-truth char ids for next-character loss.  Shifted internally.
            char_logits_to_keep (`int` or `torch.Tensor`, *optional*, defaults to 0):
                Same as ``logits_to_keep`` but for the char-level heads
                (``char_lm_head``, ``cle_lm_head``).
            cle_labels (`torch.LongTensor` of shape `(batch, char_seq_len)`, *optional*):
                Ground-truth CLE class ids for the CLE classification loss.
            distogram_labels (`torch.LongTensor` of shape `(batch, char_seq_len, char_seq_len)`, *optional*):
                Ground-truth distance-bin indices for the distogram head.
                Each value is a bin index in ``[0, distogram_bins_num)``.
            repr_char_idx (`torch.LongTensor`, *optional*):
                Token → representative-char mapping.
            use_cache (`bool`, *optional*):
                Whether to populate and return KV caches.

        Returns:
            [`XYZForCausalLMOutput`]:
                - **loss** — combined next-token + next-character + aux CE loss.
                - **logits** — next-token logits (used by `generate()`).
                - **char_logits** — next-character logits.
                - **cle_logits** — CLE classification logits.
                - **distogram_logits** — pairwise distance-bin logits
                  of shape `(batch, char_seq_len, char_seq_len, distogram_bins_num)`.
        """
        outputs: XYZModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            char_input_ids=char_input_ids,
            char_attention_mask=char_attention_mask,
            char_position_ids=char_position_ids,
            char_past_key_values=char_past_key_values,
            char_inputs_embeds=char_inputs_embeds,
            repr_char_idx=repr_char_idx,
            use_cache=use_cache,
            **kwargs,
        )

        # trunk
        hidden_states = outputs.last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(
                logits=logits,
                labels=labels,
                vocab_size=self.config.vocab_size,
                **kwargs,
            )

        # decoder
        aux_loss, aux_logits = {}, {}

        if self.config.has_characterization:
            char_hidden_states = outputs.char_last_hidden_state
            # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
            slice_indices = (
                slice(-char_logits_to_keep, None) if isinstance(char_logits_to_keep, int) else char_logits_to_keep
            )

            if self.config.has_char_lm_head:
                char_logits = self.char_lm_head(char_hidden_states[:, slice_indices, :])
                if char_labels is not None:
                    with self.num_items_in_batch(
                        kwargs, outputs.char_last_hidden_state.size(-2) / outputs.last_hidden_state.size(-2)
                    ):
                        aux_loss["char_loss"] = self.loss_function(
                            logits=char_logits,
                            labels=char_labels,
                            vocab_size=self.config.vocab_size,
                            **kwargs,
                        )
                aux_logits["char_logits"] = char_logits
            if self.config.has_cle_lm_head:
                cle_logits = self.cle_lm_head(char_hidden_states[:, slice_indices, :])
                if cle_labels is not None:
                    with self.num_items_in_batch(
                        kwargs, outputs.char_last_hidden_state.size(-2) / outputs.last_hidden_state.size(-2)
                    ):
                        aux_loss["cle_loss"] = self.loss_function(
                            logits=cle_logits,
                            labels=cle_labels,
                            vocab_size=self.config.cle_vocab_size,
                            shift_labels=cle_labels,  # FIX: Fake the `ForCausalLMLoss`
                            **kwargs,
                        )
                aux_logits["cle_logits"] = cle_logits

            if self.config.has_distogram_lm_head:
                # pairwise outer sum: (B, L, H) -> (B, L, L, H) -> (B, L, L, num_bins)
                # h = char_hidden_states
                # pair_repr = h.unsqueeze(1) + h.unsqueeze(2)
                distogram_logits = self.distogram_head(char_hidden_states[:, slice_indices, :])
                if distogram_labels is not None:
                    ignore_index = kwargs.get("ignore_index", -100)
                    # shift_distogram_labels = nn.functional.pad(
                    #     distogram_labels, (0, 1, 0, 1), value=ignore_index
                    # )
                    # shift_distogram_labels = shift_distogram_labels[..., 1:, 1:].contiguous()
                    with self.num_items_in_batch(
                        kwargs, outputs.char_last_hidden_state.size(-2) / outputs.last_hidden_state.size(-2)
                    ):
                        num_items_in_batch = kwargs.get("num_items_in_batch")
                    if num_items_in_batch is None:
                        aux_loss["distogram_loss"] = self.loss_function(
                            logits=distogram_logits,
                            labels=distogram_labels,
                            vocab_size=self.config.distogram_bins_num,
                            shift_labels=distogram_labels,  # FIX: Fake the `ForCausalLMLoss`
                            **kwargs,
                        )
                    else:
                        eps = 1e-8
                        distogram_loss = nn.functional.cross_entropy(
                            distogram_logits.reshape(-1, self.config.distogram_bins_num),
                            distogram_labels.reshape(-1),
                            ignore_index=ignore_index,
                            reduction="none",
                        ).view_as(distogram_labels)
                        distogram_loss = (
                            distogram_loss.sum(-1) / ((distogram_labels != ignore_index).sum(-1) + eps)
                        ).sum()
                        # just in case users pass an int for num_items_in_batch, which could be the case for custom trainer
                        if torch.is_tensor(num_items_in_batch):
                            num_items_in_batch = num_items_in_batch.to(distogram_loss.device)
                        aux_loss["distogram_loss"] = distogram_loss / num_items_in_batch
                    # aux_loss["distogram_loss"] = self.loss_function(
                    #     logits=distogram_logits,
                    #     labels=distogram_labels,
                    #     vocab_size=self.config.distogram_bins_num,
                    #     labels=distogram_labels,
                    #     **kwargs,
                    # )
                aux_logits["distogram_logits"] = distogram_logits

        if loss is not None and aux_loss:
            loss = loss + sum(aux_loss.values())
        elif aux_loss:
            loss = sum(aux_loss.values())

        return XYZCausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
            offset_mapping=kwargs.get("offset_mapping"),
            char_past_key_values=outputs.char_past_key_values,
            char_hidden_states=outputs.char_hidden_states,
            char_attentions=outputs.char_attentions,
            **aux_logits,
            **aux_loss,
        )

    @contextlib.contextmanager
    def num_items_in_batch(self, kwargs, amplify: float | None):
        if "num_items_in_batch" in kwargs:
            num_items_in_batch = kwargs["num_items_in_batch"]
            if amplify is not None:
                kwargs["num_items_in_batch"] = num_items_in_batch * amplify
            else:
                kwargs["num_items_in_batch"] = None
        yield kwargs
        if "num_items_in_batch" in kwargs:
            kwargs["num_items_in_batch"] = num_items_in_batch

    def prepare_inputs_for_generation(
        self,
        input_ids: torch.LongTensor,
        next_sequence_length: int | None = None,
        past_key_values: Cache | None = None,
        attention_mask: torch.LongTensor | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        is_first_iteration: bool | None = False,
        offset_mapping: torch.LongTensor | None = None,
        processor: XYZProcessor | None = None,
        **kwargs,
    ):
        model_inputs = super().prepare_inputs_for_generation(
            input_ids=input_ids,
            next_sequence_length=next_sequence_length,
            past_key_values=past_key_values,
            attention_mask=attention_mask,
            inputs_embeds=inputs_embeds,
            is_first_iteration=is_first_iteration,
            **kwargs,
        )
        if not self.config.has_characterization:
            return model_inputs

        # append offset_mapping
        if not is_first_iteration:  # not prefill stage
            tokenized = processor.to_tokenization(
                processor.to_example(model_inputs["input_ids"][:, -1:]), generate=True
            )
            tokenized["offset_mapping"] = tokenized["offset_mapping"].to(device=offset_mapping.device)
            # if kwargs.get("use_cache"):
            tokenized["offset_mapping"] = tokenized["offset_mapping"] + offset_mapping[:, -1:, -1:]
            offset_mapping = torch.cat((offset_mapping, tokenized["offset_mapping"]), dim=1)
            # else:
            #     offset_mapping = tokenized["offset_mapping"]
        # make char-level inputs
        model_inputs.update(offset_mapping=offset_mapping)
        model_inputs.update(
            processor.to_characterization(processor.to_example(input_ids), model_inputs, generate=True)
        )
        return model_inputs

    def _update_model_kwargs_for_generation(
        self,
        outputs: XYZCausalLMOutputWithPast,
        model_kwargs: dict,
        is_encoder_decoder: bool = False,
        num_new_tokens: int = 1,
    ) -> dict:
        model_kwargs = super()._update_model_kwargs_for_generation(
            outputs, model_kwargs, is_encoder_decoder=is_encoder_decoder, num_new_tokens=num_new_tokens
        )
        if outputs.offset_mapping is not None:
            model_kwargs["offset_mapping"] = outputs.offset_mapping
        return model_kwargs


class XYZForSequenceClassification(GenericForSequenceClassification, XYZPreTrainedModel):
    pass


@auto_docstring
@dataclass
class XYZTokenClassifierOutput(TokenClassifierOutput):
    """
    Output of [`XYZForTokenClassification`].

    Extends [`TokenClassifierOutput`] with character-granularity logits and
    hidden states for the auxiliary next-character prediction head.

    lm_output (`XYZCausalLMOutputWithPast`, *optional*):
        Full causal-LM output from the U-Net backbone, including next-token
        logits (``logits``) and next-character logits (``char_logits``)
    cle_logits (`torch.FloatTensor` of shape `(batch, char_seq_len, cle_vocab_size)`, *optional*):
        CLE (Cα–Local–Environment) classification logits from the
        auxiliary CLE head.
    distogram_logits (`torch.FloatTensor` of shape `(batch, char_seq_len, char_seq_len, distogram_bins_num)`, *optional*):
        Pairwise residue–residue distance-bin logits from the distogram
        head.
    """

    lm_output: XYZCausalLMOutputWithPast | None = None
    cle_logits: torch.FloatTensor | None = None
    distogram_logits: torch.FloatTensor | None = None


class XYZForTokenClassification(GenericForTokenClassification, XYZPreTrainedModel):
    pass


__all__ = [
    "XYZPreTrainedModel",
    "XYZModelOutputWithPast",
    "XYZModel",
    "XYZCausalLMOutputWithPast",
    "XYZForCausalLM",
    "XYZForSequenceClassification",
    "XYZTokenClassifierOutput",
    "XYZForTokenClassification",
]
