#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/xyz/modular_xyz.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_xyz.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
import functools
import random

from proxyz.utils import attr, compose

from transformers.processing_utils import ProcessorMixin
from transformers.utils import logging


logger = logging.get_logger(__name__)


class XYZProcessor(ProcessorMixin):
    """Processes protein sequences at both amino-acid and BPE-token granularity.

    Inherits ``ProcessorMixin`` so it supports ``save_pretrained`` /
    ``from_pretrained`` out of the box.  The wrapped BPE tokenizer is
    persisted alongside the processor config.

    ``AutoProcessor.from_pretrained(dir)`` works as long as *proxyz* is
    importable (the ``auto_map`` entry in *preprocessor_config.json*
    points to ``proxyz.processor.XYZProcessor``).
    """

    attributes = ["tokenizer"]
    tokenizer_class = "AutoTokenizer"

    FIM_PREFIX = "<fim_prefix>"
    FIM_SUFFIX = "<fim_suffix>"
    FIM_MIDDLE = "<fim_middle>"
    FIM_TOKENS = [FIM_PREFIX, FIM_SUFFIX, FIM_MIDDLE]

    def __init__(self, tokenizer, **kwargs):
        tokenizer.add_special_tokens({"additional_special_tokens": self.FIM_TOKENS})
        logger.info(f"Added FIM tokens: {self.FIM_TOKENS} to tokenizer. (vocabu size: {len(tokenizer)})")

        super().__init__(tokenizer, **kwargs)

    def __call__(
        self,
        text: str | list[str],
        *,
        bpe_dropout: float | None = None,
        char_apply: bool = False,
        fim_apply: bool = False,
        fim_spm_rate: float = 0.5,
        fim_sft_style: bool = False,
        max_length: int | None = None,
        **kwargs,
    ) -> dict:
        text_process_fn = [functools.partial(self.apply_crop, max_length=max_length)]
        if fim_apply:
            text_process_fn += [functools.partial(self.apply_fim, spm_rate=fim_spm_rate)]
        text_process_fn = compose(*text_process_fn)
        if isinstance(text, str):
            text = [text]

        wrapped = [f"{self.tokenizer.bos_token}{text_process_fn(t)}{self.tokenizer.eos_token}" for t in text]

        def tokenize_with_dropout(dropout, prefix=""):
            with attr(self.tokenizer.backend_tokenizer.model, dropout=dropout):
                tokenized = self.tokenizer(
                    wrapped,
                    truncation=True,
                    return_tensors="pt",
                    padding=True,
                    return_offsets_mapping=char_apply,
                )
            tokenized["labels"] = tokenized["input_ids"].where(tokenized["attention_mask"] > 0, -100)
            if fim_apply and fim_sft_style:
                middle_pos = (tokenized["labels"] == self.tokenizer.convert_tokens_to_ids(self.FIM_MIDDLE)).cumsum(1)
                tokenized["labels"] = tokenized["labels"].where(
                    middle_pos.cumsum(1) > 1,
                    -100,  # the <fim_middle> is excluded
                )
            return {f"{prefix}{k}": v for k, v in tokenized.items()}

        tokenized = tokenize_with_dropout(bpe_dropout, prefix="")
        if char_apply:
            tokenized.update(tokenize_with_dropout(1.0, prefix="char_"))

            # Align characters with tokenized *text*
            tokenized["char_to_token_idx"] = tokenized["char_attention_mask"].new_zeros(
                tokenized["char_attention_mask"].size()
            )
            tokenized["repr_char_idx"] = tokenized["attention_mask"].new_zeros(tokenized["attention_mask"].size())
            for k in range(len(text)):
                i, j = 0, 0
                while i < len(tokenized["offset_mapping"][k]) and j < len(tokenized["char_offset_mapping"][k]):
                    if tokenized["attention_mask"][k, i] == 0:
                        i += 1
                    elif tokenized["char_attention_mask"][k, j] == 0:
                        j += 1
                    else:
                        si, ei = tokenized["offset_mapping"][k, i]
                        sj, ej = tokenized["char_offset_mapping"][k, j]
                        if si <= sj and ej <= ei:
                            tokenized["char_to_token_idx"][k, j] = i
                            if ej == ei:
                                tokenized["repr_char_idx"][k, i] = j
                            j += 1
                        elif ei <= sj:
                            i += 1
                        else:
                            assert False, (text[k], i, j)

            del tokenized["char_offset_mapping"]
            del tokenized["offset_mapping"]

        return tokenized

    def apply_fim(self, text: str, spm_rate: float = 0.5) -> str:
        """Split content into prefix/middle/suffix and rearrange for FIM training.
        Prefix or suffix may be empty, but middle is always non-empty."""
        n = len(text)
        cut1 = random.randint(0, n - 1)
        cut2 = random.randint(cut1 + 1, n)
        prefix, middle, suffix = text[:cut1], text[cut1:cut2], text[cut2:]

        is_spm = random.random() < spm_rate
        if is_spm:
            # SPM: <BOS><fim_suffix><suffix><fim_prefix><prefix><fim_middle><middle><EOS>
            first_tag, second_tag = self.FIM_SUFFIX, self.FIM_PREFIX
            first, second = suffix, prefix
        else:
            # PSM: <BOS><fim_prefix><prefix><fim_suffix><suffix><fim_middle><middle><EOS>
            first_tag, second_tag = self.FIM_PREFIX, self.FIM_SUFFIX
            first, second = prefix, suffix

        return first_tag + first + second_tag + second + self.FIM_MIDDLE + middle

    def apply_crop(self, text: str, max_length: int | None = None):
        n = len(text)
        if max_length and max_length < n:
            k = random.randint(0, n - max_length)
            text = text[k : k + max_length]
        return text


__all__ = ["XYZProcessor"]
