#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/xyz/modular_xyz.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_xyz.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
import random

import torch
from proxyz.utils import attr

from transformers.processing_utils import ProcessorMixin
from transformers.utils import logging


logger = logging.get_logger(__name__)


class XYZProcessor(ProcessorMixin):
    """Processes protein sequences at both amino-acid and BPE-token granularity.

    Inherits ``ProcessorMixin`` so it supports ``save_pretrained`` /
    ``from_pretrained`` out of the box.  The wrapped BPE tokenizer is
    persisted alongside the processor config.

    ``AutoProcessor.from_pretrained(dir)`` works as long as *proxyz* is
    importable (the ``auto_map`` entry in *preprocessor_config.json*
    points to ``proxyz.processor.XYZProcessor``).
    """

    attributes = ["tokenizer"]
    tokenizer_class = "AutoTokenizer"

    FIM_PREFIX = "<fim_prefix>"
    FIM_SUFFIX = "<fim_suffix>"
    FIM_MIDDLE = "<fim_middle>"
    FIM_TOKENS = [FIM_PREFIX, FIM_SUFFIX, FIM_MIDDLE]

    def __init__(self, tokenizer, text_column: str = "text", features: list[str] = None, **kwargs) -> None:
        tokenizer.add_special_tokens({"additional_special_tokens": self.FIM_TOKENS})
        logger.info(f"Added FIM tokens: {self.FIM_TOKENS} to tokenizer. (vocabu size: {len(tokenizer)})")

        super().__init__(tokenizer, **kwargs)

        self.text_column = text_column
        self.features = features
        self.ignore_index = kwargs.get("ignore_index", -100)

        self.distogram_bins = torch.linspace(
            kwargs.get("distogram_bins_min", 2.3125),
            kwargs.get("distogram_bins_max", 21.6875),
            steps=kwargs.get("distogram_bins_num", 64) - 1,
        )

    def __call__(
        self,
        examples: dict,
        *,
        bpe_dropout: float | None = None,
        char_apply: bool = False,
        fim_apply: bool = False,
        fim_spm_rate: float = 0.5,
        fim_sft_style: bool = False,
        max_length: int | None = None,
        **kwargs,
    ) -> dict:
        examples = self.apply_crop(examples, max_length=max_length)
        if fim_apply:
            examples = self.apply_fim(examples, spm_rate=fim_spm_rate)
        examples = self.apply_wrap(examples)

        def tokenize_with_dropout(dropout, prefix=""):
            with attr(self.tokenizer.backend_tokenizer.model, dropout=dropout):
                tokenized = self.tokenizer(
                    examples[self.text_column],
                    truncation=True,
                    return_tensors="pt",
                    padding=True,
                    return_offsets_mapping=char_apply,
                )
            tokenized["labels"] = tokenized["input_ids"].where(tokenized["attention_mask"] > 0, self.ignore_index)
            if fim_apply and fim_sft_style:
                middle_pos = (tokenized["labels"] == self.tokenizer.convert_tokens_to_ids(self.FIM_MIDDLE)).cumsum(1)
                tokenized["labels"] = tokenized["labels"].where(
                    middle_pos.cumsum(1) > 1,
                    self.ignore_index,  # the <fim_middle> is excluded
                )
            return {f"{prefix}{k}": v for k, v in tokenized.items()}

        tokenized = tokenize_with_dropout(bpe_dropout, prefix="")
        if char_apply:
            tokenized.update(tokenize_with_dropout(1.0, prefix="char_"))

            # Align characters with tokenized *text*
            tokenized["char_to_token_idx"] = tokenized["char_attention_mask"].new_zeros(
                tokenized["char_attention_mask"].size()
            )
            tokenized["repr_char_idx"] = tokenized["attention_mask"].new_zeros(tokenized["attention_mask"].size())
            # FIX: use torch.searchsorted instead
            for k in range(len(examples[self.text_column])):
                i, j = 0, 0
                while i < len(tokenized["offset_mapping"][k]) and j < len(tokenized["char_offset_mapping"][k]):
                    if tokenized["attention_mask"][k, i] == 0:
                        i += 1
                    elif tokenized["char_attention_mask"][k, j] == 0:
                        j += 1
                    else:
                        si, ei = tokenized["offset_mapping"][k, i]
                        sj, ej = tokenized["char_offset_mapping"][k, j]
                        if si <= sj and ej <= ei:
                            tokenized["char_to_token_idx"][k, j] = i
                            if ej == ei:
                                tokenized["repr_char_idx"][k, i] = j
                            j += 1
                        elif ei <= sj:
                            i += 1
                        else:
                            assert False, (text[k], i, j)

            del tokenized["char_offset_mapping"]
            del tokenized["offset_mapping"]

        # copy features
        if self.features is not None:

            def feat_collate(feat, is_label: bool = False):
                if isinstance(feat, tuple):
                    return tuple(feat_collate(feat[t]) for t in range(len(feat)))
                max_len = max(feat[k].shape[0] for k in range(len(feat)))
                for k in range(len(feat)):
                    pad = feat[k].new_full(
                        (max_len - feat[k].shape[0], *feat[k].shape[1:]),
                        self.ignore_index if is_label else 0,
                    )
                    feat[k] = torch.cat((feat[k], pad))
                return torch.stack(feat)

            for column in self.features:
                if column in examples:
                    tokenized[column] = feat_collate(examples[column], "labels" in column)

            if "distogram_labels" in self.features:
                if "distogram_labels" in tokenized:
                    tokenized["distogram_labels"] = self.to_distogram(*tokenized["distogram_labels"])

        return tokenized

    def apply_fim(self, examples: dict, spm_rate: float = 0.5) -> dict:
        """Split content into prefix/middle/suffix and rearrange for FIM training.
        Prefix or suffix may be empty, but middle is always non-empty."""
        for idx, text in enumerate(examples[self.text_column]):
            n = len(text)
            cut1 = random.randint(0, n - 1)
            cut2 = random.randint(cut1 + 1, n)
            prefix, middle, suffix = text[:cut1], text[cut1:cut2], text[cut2:]

            is_spm = random.random() < spm_rate
            if is_spm:
                # SPM: <BOS><fim_suffix><suffix><fim_prefix><prefix><fim_middle><middle><EOS>
                first_tag, second_tag = self.FIM_SUFFIX, self.FIM_PREFIX
                first, second = suffix, prefix
            else:
                # PSM: <BOS><fim_prefix><prefix><fim_suffix><suffix><fim_middle><middle><EOS>
                first_tag, second_tag = self.FIM_PREFIX, self.FIM_SUFFIX
                first, second = prefix, suffix

            examples[self.text_column][idx] = first_tag + first + second_tag + second + self.FIM_MIDDLE + middle
            if self.features is not None:

                def feat_fim(feat, is_label: bool = False):
                    pad = feat.new_full((1, *feat.shape[1:]), self.ignore_index if is_label else 0)
                    if is_spm:
                        return torch.cat(
                            (
                                pad,
                                feat[cut2:, ...],
                                pad,
                                feat[:cut1, ...],
                                pad,
                                feat[cut1:cut2, ...],
                            )
                        )
                    return torch.cat(
                        (
                            pad,
                            feat[:cut1, ...],
                            pad,
                            feat[cut2:, ...],
                            pad,
                            feat[cut1:cut2, ...],
                        )
                    )

                for column in self.features:
                    if column in examples:
                        if isinstance(examples[column], tuple):
                            for t in range(len(examples[column])):
                                examples[column][t][idx] = feat_fim(examples[column][t][idx])
                        else:
                            examples[column][idx] = feat_fim(examples[column][idx], "labels" in column)
        return examples

    def apply_crop(self, examples: dict, max_length: int | None = None) -> dict:
        for idx, text in enumerate(examples[self.text_column]):
            n = len(text)
            if max_length and max_length < n:
                cut = random.randint(0, n - max_length)
                text = text[cut : cut + max_length]
                examples[self.text_column][idx] = text
                if self.features is not None:

                    def feat_crop(feat):
                        return feat[cut : cut + max_length, ...]

                    for column in self.features:
                        if column in examples:
                            if isinstance(examples[column], tuple):
                                for t in range(len(examples[column])):
                                    examples[column][t][idx] = feat_crop(examples[column][t][idx])
                            else:
                                examples[column][idx] = feat_crop(examples[column][idx])
        return examples

    def apply_wrap(self, examples: dict) -> dict:
        for idx, text in enumerate(examples[self.text_column]):
            examples[self.text_column][idx] = f"{self.tokenizer.bos_token}{text}{self.tokenizer.eos_token}"
            if self.features is not None:

                def feat_wrap(feat, is_label: bool = False):
                    pad = feat.new_full((1, *feat.shape[1:]), self.ignore_index if is_label else 0)
                    return torch.cat((pad, feat, pad))

                for column in self.features:
                    if column in examples:
                        if isinstance(examples[column], tuple):
                            for t in range(len(examples[column])):
                                examples[column][t][idx] = feat_wrap(examples[column][t][idx])
                        else:
                            examples[column][idx] = feat_wrap(examples[column][idx], "labels" in column)
        return examples

    def to_distogram(self, pseudo_beta, pseudo_beta_mask):
        distogram_labels = torch.cdist(pseudo_beta, pseudo_beta)
        distogram_labels = (distogram_labels[..., None] > self.distogram_bins).sum(-1)
        return distogram_labels.where(
            pseudo_beta_mask[..., :, None] * pseudo_beta_mask[..., None, :], self.ignore_index
        )


__all__ = ["XYZProcessor"]
